# Generated by Django 5.2.1 on 2025-05-11 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], default='WRL', max_length=3, unique=True, verbose_name='Categoria')),
                ('category_color', models.CharField(default='#000000', max_length=7, verbose_name='Cor')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('abstract', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagem')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('in_carousel', models.BooleanField(default=False, verbose_name='Slide')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacar')),
                ('is_sponsored', models.BooleanField(default=False, verbose_name='Patrocinada')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], default='WRL', max_length=3, unique=True, verbose_name='Categoria')),
                ('category_color', models.CharField(default='#000000', max_length=7, verbose_name='Cor')),
                ('section', models.CharField(db_index=True, max_length=255, verbose_name='Seção')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('abstract', models.TextField(verbose_name='Resumo')),
                ('news_url', models.URLField(unique=True, verbose_name='Link da matéria')),
                ('image_url', models.URLField(verbose_name='Url da imagem')),
                ('published_date', models.DateTimeField(verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name': 'Notícias de terceiros',
                'ordering': ['-published_date'],
            },
        ),
    ]
