# Generated by Django 5.2.1 on 2025-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='abstract',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resumo'),
        ),
    ]
