# Generated by Django 5.2.1 on 2025-05-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='in_slide',
            field=models.BooleanField(default=False, verbose_name='Slide'),
        ),
    ]
