# Generated by Django 5.2.1 on 2025-05-11 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], max_length=3, unique=True, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='ThirdPartyNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(db_index=True, max_length=255, verbose_name='Seção')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('abstract', models.TextField(verbose_name='Resumo')),
                ('news_url', models.URLField(unique=True, verbose_name='Link da matéria')),
                ('image_url', models.URLField(verbose_name='Url da imagem')),
                ('published_date', models.DateTimeField(verbose_name='Data de publicação')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thirdpartynews', to='news.category', verbose_name='Categoria da Notícia')),
            ],
            options={
                'verbose_name': 'Notícias de terceiros',
                'ordering': ['-published_date'],
            },
        ),
    ]
