# Generated by Django 5.2.1 on 2025-05-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_category_name_thirdpartynews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartynews',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='category_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_name',
            field=models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], default='WRL', max_length=3, unique=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='thirdpartynews',
            name='category_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='thirdpartynews',
            name='category_name',
            field=models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], default='WRL', max_length=3, unique=True, verbose_name='Nome'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
