# Generated by Django 5.2.1 on 2025-05-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_in_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='in_slide',
            new_name='in_carousel',
        ),
    ]
