# Generated by Django 5.2.1 on 2025-05-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_in_slide_news_in_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
