# Generated by Django 5.2.1 on 2025-05-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_thirdpartynews_category_remove_news_category_and_more'),
        ('news', '0010_news_views'),
    ]

    operations = [
    ]
