<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-11 19:19
=======
# Generated by Django 5.2.1 on 2025-05-11 20:11
>>>>>>> origin/dev

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('news', '0011_merge_20250511_1619'),
=======
        ('news', '0011_merge_20250511_1711'),
>>>>>>> origin/dev
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category_name',
<<<<<<< HEAD
            field=models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], default='WRL', max_length=3, unique=True, verbose_name='Categoria'),
=======
            field=models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], default='TPN', max_length=3, unique=True, verbose_name='Categoria'),
>>>>>>> origin/dev
        ),
        migrations.AlterField(
            model_name='thirdpartynews',
            name='category_name',
<<<<<<< HEAD
            field=models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], default='WRL', max_length=3, unique=True, verbose_name='Categoria'),
=======
            field=models.CharField(choices=[('SCI', 'Ciencias'), ('BIS', 'Negócios'), ('WRL', 'Mundo'), ('HEL', 'Saúde'), ('TPN', 'Noticias de terceiros')], default='TPN', max_length=3, unique=True, verbose_name='Categoria'),
>>>>>>> origin/dev
        ),
    ]
