# Generated by Django 5.2.1 on 2025-05-09 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(db_index=True, max_length=255, verbose_name='Seção')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('abstract', models.TextField(verbose_name='Resumo')),
                ('news_url', models.URLField(unique=True, verbose_name='Link da matéria')),
                ('image_url', models.URLField(verbose_name='Url da imagem')),
                ('published_date', models.DateTimeField(db_index=True, verbose_name='Data de publicação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
